### ISSUE TITLE
Installing using 'sudo apt install' causes segmentation fault

### ISSUE THREAD

**Issue by turboboost55** [hreinecke/lsscsi#5]
I was trying to install `lsscsi` on my Raspberry Pi 4, running Ubuntu 20.04. I don't have a detailed log of what happened, but it got to the end where it says "processing triggers", then it said something about "update-initramfs: Generating /boot/initrd.img", and then it started printing out "segmentation fault (core dumped)" repeatedly.

Now any time I try to do anything with apt it does something very similar, for example:

```
$ sudo apt-get -f install

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up initramfs-tools (0.136ubuntu6.6) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.136ubuntu6.6) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-1058-raspi
Illegal instruction (core dumped)
Illegal instruction (core dumped)
Illegal instruction (core dumped)
<repeated>
```
My immediate need is to figure out how to clear out that failed install so I can use `apt` commands again, but of course the bigger picture would be to understand why the install failed in the first place.

**Comment by turboboost55** [comment]
I also tried running `sudo dpkg --configure -a` and got the same repeated core dumps going down the screen.

**Comment by doug-gilbert** [comment]
I don't believe your problem has anything to do with the code in lsscsi. It gets all its data from datamining in sysfs (i.e. under /sys ) with bog standard Unix calls. There is nothing in lsscsi that effects the booting of a machine so it should not trigger calls to "Setting up initramfs-tools".  Below is an example on a RPi 4 with 8GB of ram running Ubuntu 21.10,  64 bit.

root@rpi8:/tmp# apt install lsscsi
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  lsscsi
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 48.5 kB of archives.
After this operation, 114 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports impish/main arm64 lsscsi arm64 0.31-1build1 [48.5 kB]
Fetched 48.5 kB in 1s (79.7 kB/s)
Selecting previously unselected package lsscsi.
(Reading database ... 189711 files and directories currently installed.)
Preparing to unpack .../lsscsi_0.31-1build1_arm64.deb ...
Unpacking lsscsi (0.31-1build1) ...
Setting up lsscsi (0.31-1build1) ...
Processing triggers for man-db (2.9.4-2) ...

If I was asked to guess what is going on, I would be checking the SD card in the RPi. Take it to another machine and use dd to read it . If it can read from start to finish then the problem is somewhere else.

**Comment by turboboost55** [comment]
I've tried a few other things since my initial post, and I think I agree with your hunch that the SD card is corrupt.
